services:
  server:
    build:
        context: .
        dockerfile: Dockerfile.server
    ports:
      - "1337:1337"
    volumes:
      - "./content:/app/content:ro"
    command: ["python", "server.py", "-d", "/app/content"]

  client:
    build:
        context: .
        dockerfile: Dockerfile.client
    volumes:
      - "./content/downloads:/app/content/downloads"
    command: ["tail", "-f", "/dev/null"]
    depends_on:
      - server
    extra_hosts:
        - "host.docker.internal:host-gateway"